env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - import
  - react
rules:
  import/first: 2
  import/order: 2
  import/newline-after-import: 2

  # Disabled to avoid false-positives, as it has limitid capabilities for
  # detecting props definitions. At the same time, this project uses Typescript,
  # which already checks props, making this rule redundant.
  react/prop-types: "off"
settings:
  react:
    version: detect
