name: PR checks
on:
  pull_request:
    branches:
      - master
jobs:
  lint-and-types-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: yarn
      - name: Install modules
        run: yarn
      - name: Checks and tests
        run: yarn ci
